apiVersion: v1
kind: Service
metadata:
  name: projects-mongo
  labels:
    app: projects-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: projects-mongo