apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projects-mongo-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  volumeName: projects-mongo-volume