apiVersion: v1
kind: PersistentVolume
metadata:
  name: projects-mongo-volume
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  storageClassName: standard
  hostPath:
    path: /home/c/projects_mongo